# Generated by Django 3.0.5 on 2020-04-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rate',
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
