# Generated by Django 3.0.5 on 2020-04-22 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20200421_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='yanıt',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='comment',
            name='yanıt_tarihi',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='yanıtlayan',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
