# Generated by Django 3.0.5 on 2020-05-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20200422_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
