# Generated by Django 3.0.5 on 2020-05-10 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_auto_20200510_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image_com',
        ),
    ]
