# Generated by Django 3.0.5 on 2020-05-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_remove_comment_image_com'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image_com',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
