# Generated by Django 3.0.5 on 2020-05-23 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_auto_20200521_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='yanıt',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='yanıt_tarihi',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='yanıtlayan',
        ),
    ]
