# Generated by Django 3.0.5 on 2020-05-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_auto_20200524_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='yanıt',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='comment',
            name='yanıt_tarihi',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='yanıtlayan',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='subject',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
