# Generated by Django 3.0.5 on 2020-05-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_auto_20200524_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='yanıt',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='yanıt_tarihi',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='yanıtlayan',
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
