# Generated by Django 3.0.5 on 2020-05-23 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_auto_20200524_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='yanıt',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='yanıt_tarihi',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='yanıtlayan',
        ),
    ]
