# Generated by Django 3.0.5 on 2020-04-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200405_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='logo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
