# Generated by Django 3.0.5 on 2020-05-17 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_sorular'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sorular',
            new_name='FAQ',
        ),
    ]
