# Generated by Django 3.0.5 on 2020-05-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20200509_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tarih',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='vale',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
