# Generated by Django 3.0.5 on 2020-05-21 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20200521_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='tarih',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='vale',
        ),
    ]
