# Generated by Django 3.0.5 on 2020-05-21 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20200522_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='tarih',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='vale',
        ),
    ]
